### ISSUE TITLE
Roadmap Q3 2020

### ISSUE THREAD

**Issue by alexrobin** [opensensorhub/osh-js#134]
- [ ] Cleanup/remove old data sources
- [ ] Refactor folder structure (src/core; src/ext; src/vuejs)
- [ ] Generic action callbacks (for entities and view items)
  - [ ] Design
  - [ ] Implementation
- [ ] Generic reusable vue.js components on top of our views
- [ ] Improve SOS client? (rename Server class, support batch historical obs requests)
- [ ] Improve Tasking
  - [ ] SPS client
  - [ ] Auto generate generic form from tasking parameters (either SPS or STA)
  - [ ] Support websocket for command streams
- [ ] STA client
  - [ ] Design
  - [ ] HTTP implementation
  - [ ] MQTT implementation
- [ ] SWE REST API client
  - [ ] Design
  - [ ] HTTP implementation
  - [ ] MQTT/WS implementation
- [ ] Generic binary data source -> present as JSON object with fields as ArrayBuffers when it makes sense (e.g. large numerical arrays, compressed data such as video frames)

Do we even need a model for action callbacks? Should it be a pure UI thing? -> Can be useful in a multi-view environment where consistent action handling is needed across views (e.g. same behavior no matter where the item is selected), but it could still be handled at the UI level.

Actions = hover, left click, left double click, right click, drag, tap etc. so just forward UI event + entity/viewItem/dataSource info, or higher level events like select/show/hide/menu?
