### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by mdhsl** [opensensorhub/osh-js#2]
### Toolkit
- [x] Add chart View #3 [Live demo](http://opensensorhub.github.io/osh-js/Toolkit/tests/3/)
- [x] Add configuration options to leaflet #1 [Live demo](http://opensensorhub.github.io/osh-js/Toolkit/tests/1/)
- [x] Add OpenLayer View #4 [Live demo](http://opensensorhub.github.io/osh-js/Toolkit/tests/4/)
- [x] Improve synchronization Buffer
- [x] Improve H264/MP4 support
- [x] Add Entities tree
- [x] Add a range slider to control replay time
- [x] Handle connect & disconnect streams
- [x] Add Tasking View #18 [Live demo](http://opensensorhub.github.io/osh-js/Toolkit/tests/5/)
- [x] Add Data sender #19 [Live demo](http://opensensorhub.github.io/osh-js/Toolkit/tests/5/)
- [x] Change function data passing by event passing message between UI components
- [x] Change the way to pass the entity into the EntityViewer 
- [x] Call the EventManager to observer and fire events
- [x] Change the ContextualMenu class by a generic one accepting a css 
- [x] Use event message passing instead of function data passing between buffer and dataProvider
- [x] Use event message passing instead of unction data passing between DataProvider and others components
- [x] Handle dissemination into the handleEvent of the View
- [x] Check for a librairie to import javascript files dynamically (like require)
- [x] Benchmark data: function passing versus event passing
- [x] Clean osh-js repository to keep only Toolkit/Clients/Demos/Demos-old
- [x] Add support for left and right click onto OpenLayer marker
- [x] Upgrade CesiumView to match with the new architecture
- [x] Upgrade OpenLayerView to match with the new architecture
- [x] Add support for selected styler on the NVD3 View
- [ ] Add Polygon Styler
- [ ] Check for NVD3 performance issue when refreshing a graph with hundreds of points
- [ ] Add support for left and right click onto Cesium marker
- [x] Add generic SWE data provider (using new JSON format)
- [ ] Add Field of View Styler
- [x] Merge the unit test into master #52
- [x] Make an useful showcase for testing
- [x] Tasking component #53
- [x] MultiDialog #54

### VideoDisplay demo
- [x] Fix mini video viewer draggable part
- [x] Add layout to support mini video container
- [x] Add contextual menu on marker click
- [x] Add 2D/3D button
- [ ] Add describe sensor request and link 
- [ ] Handle the out of window box dialog

### Important Issues
- [x] FFMpegView - Import Script for WebWorker #47
- [x] FFMpegView - Module missing #46
- [x] FFMpegView - Crash if too many views are loaded #65
- [x] FFMpegView - WebWorker concurrent error #66

### Styling
- [ ] General framework for generating default styling rules from sensor/SOS metadata
- [ ] Define generic interface for consumers of graphic objects (views implement it)
- [ ] Add styler customizer panel
